### PR TITLE
Executables

### PR DESCRIPTION
**Pull request by Cmheidelberg**
New command: `executables`:
  - This is a separate command for adding code files to the yaml.
  - Replaces the need to add code files from `inputs` command
  - New features:
    - Automatically adds code files detected by `trace` command
    - users can add extra executable files that werent detected by mic (similar to how `inputs` and `outputs` command works)
    - `--show` option list code files already logged by mic
    - `--remove` option removes executables from yaml without forcing the user to make manual edits 
  - Added test cases for `executables` commands
  - Added documentation for `executables` command (docs/commands/executables.md). Can be viewed from mkdocs

Reformatted docs:
I got carried away with the docs and forgot to open up another branch for this. I reformatted the docs to have a separate page for each mic command. This will show a detailed description for the commands as well as their options and examples of various use cases. configure.md and executables.md are examples of what im thinking about. 
I added a page for each command but I dont want to populate them until this gets approved

### CODE REVIEW

**Comment by dgarijo** [comment]
Sorry, @Cmheidelberg but I don't understand the rationale for the `executables` command. Which issue is it addressing? Has this been discussed?
the trace command already tracks all the files required for execution. In which case do we need executables?

Also, the `inputs` commands is probably still needed to create the abstraction that does not expose certain inputs in a configuration

**Comment by Cmheidelberg** [comment]
This doesnt replace the `inputs` command. It separates its functionality. Right now when you run `inputs` it will add the detected input files **and** code files to the yaml. This splits that functionality making it a bit more explicit that mic is adding code files to the yaml and also grands the user more control to  to remove incorrectly added executables or add ones that werent detected without the need to edit the mic.yaml directly. 

The issue is on github (#249 ). This stems back to the issue #199. The problem with removing mic asking the user if something is a executable is that if mic misses something the user has no control add the code to mic without understanding how to edit the yaml.

**Comment by sirspock** [comment]
@Cmheidelberg  I think the issue 249 is not selected for this week. Right?

**Comment by sirspock** [comment]
I see that you are trying to do. But, I dont like the idea to add new command.

**Comment by sirspock** [comment]
But, it can good option. But it needs more discussion. In my opinion, now we cannot add a new command.

**Comment by dgarijo** [comment]
I think we need more discussion; I still don't understand very well what this does and adding a new command may be disruptive for the workflow.

**Pull request closed without merging**
